//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicPerformance
    {
        public int PerformanceID { get; set; }
        public int StudentID { get; set; }
        public int StudyGroupID { get; set; }
        public System.DateTime GradeDate { get; set; }
        public Nullable<int> Grade { get; set; }
        public bool Attendance { get; set; }
        public string Comment { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual StudyGroups StudyGroups { get; set; }
    }
}
