//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPerformanceView
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string GroupName { get; set; }
        public string SubjectName { get; set; }
        public string TeacherName { get; set; }
        public System.DateTime GradeDate { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Attendance { get; set; }
        public string Comment { get; set; }
    }
}
