//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyGroups()
        {
            this.AcademicPerformance = new HashSet<AcademicPerformance>();
        }
    
        public int StudyGroupID { get; set; }
        public int GroupID { get; set; }
        public int SubjectID { get; set; }
        public int TeacherID { get; set; }
        public string AcademicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicPerformance> AcademicPerformance { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
